version: '3.8'

services:
  web:
    build: 
      context: ./app
      dockerfile: Dockerfile
    command: gunicorn registrator.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
      
  db:
    image: postgres:15.4
    volumes:
      - ./postgres_data/:/var/lib/postgresql/data/
    env_file:
      - ./.env
    

  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - "80:80"
    depends_on:
      - web

  tgbot:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: python main.py
    volumes:
      - ./:/usr/src/app
    restart: unless-stopped
    env_file:
      - ./.env
    depends_on:
      - db
      - web


volumes:
  postgres_data:
    driver: local
  static_volume:
  media_volume: